FROM ubuntu

RUN apt-get update

RUN apt-get install -y python3-pip python3-dev

RUN apt-get install g++ -y

RUN apt-get install cmake -y
 
RUN apt-get install python-pip -y

RUN pip install cffi

RUN pip install numpy


